### ISSUE TITLE
Pronto na logikę

### ISSUE THREAD

**Issue by annalg** [Filios92/ProjektMO#1]
Wydaje mi się, że tam wciąż jest coś nie tak z tą logiką - faili w zasadzie już nie ma, ale koniec prawie zawsze == początkowi... Bez względu na pop_size. Albo coś przeoczyłam?
params = {
        'graph'           : graph,
        'start_idx'       : 1,
        'end_idx'         : 4,
        'max_flights'     : 5,
        'cost_weight'     : 2,
        'time_weight'     : 1,
        'pop_size'        : ZMIENNE,
        'generations'     : 10,
        'mutation_rate'   : 0.015,
        'tournament_size' : 5,
        'elitism'         : True
    }
Poza tym 50 iteracji na tych samych danych trwa 20s - za szybko coś.

**Comment by annalg** [comment]
![log](https://cloud.githubusercontent.com/assets/7063863/8022075/8f640520-0cbc-11e5-83c5-1b95fc67d4d7.PNG)
Załączam wycinek logów :D

**Comment by Filios92** [comment]
Już jest dobrze. :D
