### ISSUE TITLE
Wpadanie w nieskończone pętle 

### ISSUE THREAD

**Issue by annalg** [Filios92/ProjektMO#2]
Mam wrażenie, że on wciąż wpada w nieskończone pętle... Ustaw może jakiś timeout, counter albo coś. Bo testy wykazały, że owszem failure ratio maleje wraz z rosnącym rozmiarem populacji, ale po 3 iteracjach parametru się wysypał i musiałam test puścić od zera. A do rana nie mam zamiaru go co chwile od nowa puszczać :P

**Comment by Filios92** [comment]
Na czym się zatrzymuje?

07.06.2015, annalg notifications@github.com napisał(a):

**Comment by annalg** [comment]
Jak znowu się zawiesi to wrzucę screena tracebacku... ale z tego, co kojarzę, to przy szukaniu ścieżki - przy jakiejś nierówności

**Comment by Filios92** [comment]
Ok, chyba wiem co było nie tak, sprawdź teraz. Ale podesłać tracebacka możesz jeśli się wywali.

**Comment by annalg** [comment]
File "C:\Python34\GraphManager.py", line 95, in find_random_path
    newpath = self.find_random_path(node[1], end, path, flights)
  File "C:\Python34\GraphManager.py", line 95, in find_random_path
    newpath = self.find_random_path(node[1], end, path, flights)
  File "C:\Python34\GraphManager.py", line 95, in find_random_path
    newpath = self.find_random_path(node[1], end, path, flights)
  File "C:\Python34\GraphManager.py", line 95, in find_random_path
    newpath = self.find_random_path(node[1], end, path, flights)
  File "C:\Python34\GraphManager.py", line 95, in find_random_path
    newpath = self.find_random_path(node[1], end, path, flights)
  File "C:\Python34\GraphManager.py", line 95, in find_random_path
    newpath = self.find_random_path(node[1], end, path, flights)
  File "C:\Python34\GraphManager.py", line 92, in find_random_path
    if node[1] not in path:

**Comment by annalg** [comment]
Ale może by w końcu z tego wyszedł, nie wiem...

**Comment by Filios92** [comment]
Ale czekaj, on się tam wywala sam, czy Ty go przerywasz? :D

**Comment by Filios92** [comment]
Bo wydaje mi się, że Ty go przerywasz, a on sobie po prostu szuka rozwiązania. To może zając trochę przy dużym grafie. Powinno :D

**Comment by annalg** [comment]
Ja mu musze przerwac, bo by nigdy nie skończył - wczoraj za pierwszym razem czekałam chyba ponad godzine

**Comment by Filios92** [comment]
Wczoraj... wczoraj była inna wersja :D Ale podaj parametry

**Comment by annalg** [comment]
'max_flights'     : 20,
        'cost_weight'     : 2,
        'time_weight'     : 1,
        'pop_size'        : ZMIENNE,
        'generations'     : 10,
        'mutation_rate'   : 0.2,
        'tournament_size' : 2,
        'elitism'         : False,
        'dest_min'        : 2,
        'dest_max'        : 10

**Comment by tommy4** [comment]
O której to we wtorek dodajemy? Bo się grafikuje na przyszły tydzień..:d
7 cze 2015 22:32 "annalg" notifications@github.com napisał(a):

**Comment by annalg** [comment]
O 11.15 chyba

**Comment by Filios92** [comment]
U mnie nic takiego się nie dzieje. Losujesz graf zawsze czy masz jakiś już gotowy?

**Comment by annalg** [comment]
Mam gotowy

**Comment by Filios92** [comment]
Trzeba ustalić z nim godzinę?

**Comment by Filios92** [comment]
To daj :D

**Comment by annalg** [comment]
A tego nie wiem - może tak byłoby lepiej niż 2h tam siedzieć

**Comment by Filios92** [comment]
Paweł był chętny bardzo, żeby zanieść to, żebyśmy z pracy nie musieli się urywać :)

**Comment by annalg** [comment]
Eee... Zaraz na maila poleci

**Comment by annalg** [comment]
Ooo, to miło z jego strony :D

**Comment by Filios92** [comment]
Tu też możesz plik wrzucić

**Comment by annalg** [comment]
Nie, pisze mi, że nie supportuja tego typu :P

**Comment by annalg** [comment]
A pusha zrobie za chwile...

**Comment by annalg** [comment]
Ok, graph.txt poszedł w pushu

**Comment by Filios92** [comment]
U mnie działa, czasem dłużej myśli, ale aktualnie to nic nie powinno się zapętlać

**Comment by annalg** [comment]
Typowya odpowiedź developera :D

**Comment by annalg** [comment]
Bugi nie wychodzą od razu :P Ale tak serio, teraz iteracje pop_size przeszły bez problemu, przyiteracjach generaci teraz mocno myśli.

**Comment by annalg** [comment]
Dobra, myślę, że można zamknąć isiu - choć zmienność kolejnych rozwiązań jest wciąż fatalna - ale zobaczymy, co zrobi przy iterowaniu po mutacjach.
