### ISSUE TITLE
Graf

### ISSUE THREAD

**Issue by annalg** [Filios92/ProjektMO#3]
Jeśli chodzi o ewentualne uwagi, to można by łączyć lotniska strzałkami, ale nie wiem, ile z tym roboty - a ważniejsze są wykresy. Co z wykresami?

**Comment by pawel3ak** [comment]
No to tak - strzałkami raczej mozna tylko wtedy raczej zrobi sie miszmasz wg mnie;p co do wykresow to zaraz wrzuce do funkcjonalnosci przycisku generowanie grafu na podstawie danych (w sensie ze wykresow).

**Comment by annalg** [comment]
Ok, to jak sie wszystkie wykresy namaluja, to podeslij mi je - bo bede je musiala opisac w dokumentacji.

**Comment by pawel3ak** [comment]
Dobra - jakies szczegolne dane podpinac? czy z tego co jest na gicie zrobic serie?

**Comment by annalg** [comment]
https://www.dropbox.com/s/9vwb764mqrag420/performance.txt?dl=0
Dnia 9 czerwca 2015 20:11 pawel3ak &lt;notifications@github.com&gt; napisał(a):
Dobra - jakies szczegolne dane podpinac? czy z tego co jest na gicie zrobic serie?—

**Comment by annalg** [comment]
https://www.dropbox.com/s/9vwb764mqrag420/performance.txt?dl=0

**Comment by pawel3ak** [comment]
Ilosc tych pomiarow stała ( wsnsie wykresów w oknie?)? Uśrednianie włączyć?:p

**Comment by annalg** [comment]
tak, trzeba usrednic...
tylko hmm.. ilosc iteracji danego parametru nie jest stala niestety, bo np dla generacji sa wartosci 10, 20, 30, a dla elitarnosci tylko true false itd....
